### ISSUE TITLE
How can i use this if symbols are stripped in the binary?

### ISSUE THREAD

**Issue by HeroFluxx** [TimScriptov/ModdedPE#6]

**Comment by HeroFluxx** [comment]
Also how can we make Nmods now because of no symbols in the android version

**Comment by timscriptov** [comment]
The new version of Minecraft lacks symbols, you can write mods on json

**Comment by timscriptov** [comment]
Convert .mcpack to .nmod

**Comment by HeroFluxx** [comment]
That's very interesting 🤔

**Comment by protectoryt** [comment]
Hey i got some error while using modderpe app please make a discord server Where i can send bugs
