### ISSUE TITLE
Substrate for arm64-v8a can not work

### ISSUE THREAD

**Issue by Yalums** [TimScriptov/ModdedPE#9]
As moddedpe support arm64-v8a application,there may be some difficulty running a nativemod example when launching with MSHookfunction

**Comment by Yalums** [comment]
Screenshot: sm.ms/image/jhCmquOoQfJvaNT
This is raw file: drive.google.com/file/d/1l_LJSnOwizIcfmir40PyNpjy8N3Ti75L/view?usp=sharing

**Comment by timscriptov** [comment]
@Tcbdxh substrate deprecated. Substrate support arm7 and x86. For arm64 need use xhook

**Comment by timscriptov** [comment]
Example:

https://github.com/TimScriptov/ModdedPE/blob/ModdedPE-JAVA/app/src/main/cpp/xhook-skycolor/main.cpp

**Comment by Yalums** [comment]
> @Tcbdxh substrate deprecated. Substrate support arm7 and x86. For arm64 need use xhook

I get it,thank you(ﾟДﾟ)ﾉ
